/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class App {

    public static void main(String[] args) {
        String text = "{\"author\":\"ahmed\",\"text\":\"adfafaf\"}";
        Gson gson = new Gson();
        try {
            Reader reader = new FileReader("/Users/macbookpro/projects/401/quotes/app/src/main/resources/data.json");
            Quotes[] quotesArray = gson.fromJson(reader,Quotes[].class);
            System.out.println(quotesArray.length);
            int min = 0;
            int max = 142;
            int random_int = (int)Math.floor(Math.random()*(max-min+1)+min);
            System.out.println(quotesArray[random_int]);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
